# permissions for end users to view itworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: itworks-viewer-role
rules:
- apiGroups:
  - webapp.tkircsi
  resources:
  - itworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.tkircsi
  resources:
  - itworks/status
  verbs:
  - get
