# permissions for end users to edit itworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: itworks-editor-role
rules:
- apiGroups:
  - webapp.tkircsi
  resources:
  - itworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.tkircsi
  resources:
  - itworks/status
  verbs:
  - get
